workflows:
  android_workflow:
    name: Android Release
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore_credentials
      groups:
        - keystore_credentials
      vars:
        PACKAGE_NAME: "com.gurulink.app"
        NODE_VERSION: "18.20.3"
    cache:
      cache_paths:
        - ~/.npm
        - android/.gradle
        - node_modules
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:
      - name: Set Node version
        script: |
          echo "Using Node $NODE_VERSION"
          node --version
      - name: Install dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Sync Capacitor Android
        script: |
          npx cap sync android
      - name: Build Android release APK
        script: |
          cd android
          ./gradlew clean assembleRelease \
            -Pandroid.injected.signing.store.file=$CM_KEYSTORE_PATH \
            -Pandroid.injected.signing.store.password=$CM_KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$CM_KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$CM_KEY_PASSWORD
      - name: Build Android release AAB
        script: |
          cd android
          ./gradlew clean bundleRelease \
            -Pandroid.injected.signing.store.file=$CM_KEYSTORE_PATH \
            -Pandroid.injected.signing.store.password=$CM_KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$CM_KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$CM_KEY_PASSWORD
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - "builds@gurulink.app"
        notify:
          success: true
          failure: true

  ios_workflow:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.gurulink.app
      groups:
        - ios_credentials
      vars:
        XCODE_SCHEME: "App"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        NODE_VERSION: "18.20.3"
    cache:
      cache_paths:
        - ~/.npm
        - ~/Library/Caches/CocoaPods
        - node_modules
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:
      - name: Set Node version
        script: |
          echo "Using Node $NODE_VERSION"
          node --version
      - name: Install dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          pod install
      - name: Build and archive iOS app
        script: |
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            archive
      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            -exportOptionsPlist ios/App/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/ios/export
    artifacts:
      - ios/export/*.ipa
      - ios/App/build/**/*.dSYM
    publishing:
      email:
        recipients:
          - "builds@gurulink.app"
        notify:
          success: true
          failure: true
