workflows:
  android_workflow:
    name: Android Release
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore_credentials
      groups:
        - keystore_credentials # Define in Codemagic UI: store_file, store_password, key_alias, key_password
      vars:
        PACKAGE_NAME: "com.gurulink.app"
        NODE_VERSION: "18.20.3"
        CAPACITOR_ANDROID_VERSION: "7.0.0"
    cache:
      cache_paths:
        - ~/.npm
        - android/.gradle
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:
      - name: Set Node version
        script: |
          echo "Using Node $NODE_VERSION"
          node --version
      - name: Install dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Sync Capacitor Android
        script: |
          npx cap sync android
      - name: Build Android release APK
        script: |
          cd android
          ./gradlew clean assembleRelease -Pandroid.injected.signing.store.file=$CM_KEYSTORE_PATH \
            -Pandroid.injected.signing.store.password=$CM_KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$CM_KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$CM_KEY_PASSWORD
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - "$CM_BUILD_INITIATOR_EMAIL"
        notify:
          success: true
          failure: true
        skip_if_no_recipients: true

  ios_workflow:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.gurulink.app
      groups:
        - ios_credentials # Provide APP_STORE_CONNECT_*, CERTIFICATES, PROFILES in Codemagic UI
      vars:
        XCODE_SCHEME: "App"
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        NODE_VERSION: "18.20.3"
    cache:
      cache_paths:
        - ~/.npm
        - ~/Library/Caches/CocoaPods
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
      - name: Build IPA
        script: |
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/ios/App.xcarchive \
            archive
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/ios/App.xcarchive \
            -exportOptionsPlist ios/App/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/ios/export
    artifacts:
      - ios/export/*.ipa
      - ios/App/build/**/*.dSYM
    publishing:
      email:
        recipients:
          - "$CM_BUILD_INITIATOR_EMAIL"
        notify:
          success: true
          failure: true
        skip_if_no_recipients: true
